"""fase 7 bagian 5: tabel daily_recaps

Revision ID: 0e717dcadb03
Revises: 40ec5ab42f56
Create Date: 2026-09-19 16:21:14.629828

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0e717dcadb03"
down_revision: str | None = "40ec5ab42f56"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "daily_recaps",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("date", sa.String(length=10), nullable=False),
        sa.Column("headline", sa.Text(), nullable=False),
        sa.Column("yesterday", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("forecast", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("counts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("model", sa.String(length=100), nullable=False),
        sa.Column("token_usage", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("raw_llm", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_daily_recaps")),
        sa.UniqueConstraint("date", name="uq_daily_recap_date"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("daily_recaps")
    # ### end Alembic commands ###
