"""fase_7_4_grup_d_kolom_actionability_ioc

Revision ID: 20e63ec867dd
Revises: 32dbf203b498
Create Date: 2026-09-23 12:59:08.576155

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "20e63ec867dd"
down_revision: str | None = "32dbf203b498"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("iocs", sa.Column("actionability_score", sa.SmallInteger(), nullable=True))
    op.add_column("iocs", sa.Column("actionability_label", sa.String(length=20), nullable=True))
    op.add_column("iocs", sa.Column("recommended_action", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("iocs", "recommended_action")
    op.drop_column("iocs", "actionability_label")
    op.drop_column("iocs", "actionability_score")
    # ### end Alembic commands ###
