"""fase 7: monitored_accounts display_name/notes

Revision ID: 22b43affdcac
Revises: 9faf52bcc2a1
Create Date: 2026-09-18 19:06:11.776248

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "22b43affdcac"
down_revision: str | None = "9faf52bcc2a1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # 1 baris udah ada (seed manual/testing sebelumnya) -- server_default
    # biar ADD COLUMN NOT NULL gak gagal, dicabut abis backfill (pola sama
    # kayak migrasi ioc_allowlist_entries.added_by).
    op.add_column(
        "monitored_accounts",
        sa.Column("display_name", sa.String(length=200), nullable=False, server_default=""),
    )
    op.add_column(
        "monitored_accounts",
        sa.Column("notes", sa.Text(), nullable=False, server_default=""),
    )
    op.alter_column("monitored_accounts", "display_name", server_default=None)
    op.alter_column("monitored_accounts", "notes", server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("monitored_accounts", "notes")
    op.drop_column("monitored_accounts", "display_name")
    # ### end Alembic commands ###
