"""fase 7 bagian 3: tabel attack + ta_whitelist/ta_watchlist/ta_profiles +
ThreatActorGroup.source + CVE threat_actors/ttps/cisa_kev

Revision ID: 25d20e532710
Revises: f5a204cd523a
Create Date: 2026-09-18 23:39:15.960109

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "25d20e532710"
down_revision: str | None = "f5a204cd523a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attack_groups",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("stix_id", sa.String(length=100), nullable=False),
        sa.Column("group_id", sa.String(length=20), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("aliases", postgresql.ARRAY(sa.String(length=200)), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("created", sa.String(length=40), nullable=False),
        sa.Column("modified", sa.String(length=40), nullable=False),
        sa.Column("domains", postgresql.ARRAY(sa.String(length=20)), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attack_groups")),
    )
    op.create_index(op.f("ix_attack_groups_group_id"), "attack_groups", ["group_id"], unique=False)
    op.create_index(op.f("ix_attack_groups_stix_id"), "attack_groups", ["stix_id"], unique=True)
    op.create_table(
        "attack_mitigations",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("stix_id", sa.String(length=100), nullable=False),
        sa.Column("mitigation_id", sa.String(length=20), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("modified", sa.String(length=40), nullable=False),
        sa.Column("domains", postgresql.ARRAY(sa.String(length=20)), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attack_mitigations")),
    )
    op.create_index(
        op.f("ix_attack_mitigations_mitigation_id"),
        "attack_mitigations",
        ["mitigation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attack_mitigations_stix_id"), "attack_mitigations", ["stix_id"], unique=True
    )
    op.create_table(
        "attack_relationships",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("stix_id", sa.String(length=100), nullable=False),
        sa.Column("relationship_type", sa.String(length=50), nullable=False),
        sa.Column("source_ref", sa.String(length=100), nullable=False),
        sa.Column("source_type", sa.String(length=50), nullable=False),
        sa.Column("target_ref", sa.String(length=100), nullable=False),
        sa.Column("target_type", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("domain", sa.String(length=20), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attack_relationships")),
    )
    op.create_index(
        op.f("ix_attack_relationships_domain"), "attack_relationships", ["domain"], unique=False
    )
    op.create_index(
        op.f("ix_attack_relationships_source_ref"),
        "attack_relationships",
        ["source_ref"],
        unique=False,
    )
    op.create_index(
        op.f("ix_attack_relationships_stix_id"), "attack_relationships", ["stix_id"], unique=True
    )
    op.create_index(
        op.f("ix_attack_relationships_target_ref"),
        "attack_relationships",
        ["target_ref"],
        unique=False,
    )
    op.create_table(
        "attack_software",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("stix_id", sa.String(length=100), nullable=False),
        sa.Column("software_id", sa.String(length=20), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("software_type", sa.String(length=20), nullable=False),
        sa.Column("aliases", postgresql.ARRAY(sa.String(length=200)), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("platforms", postgresql.ARRAY(sa.String(length=50)), nullable=False),
        sa.Column("modified", sa.String(length=40), nullable=False),
        sa.Column("domains", postgresql.ARRAY(sa.String(length=20)), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attack_software")),
    )
    op.create_index(
        op.f("ix_attack_software_software_id"), "attack_software", ["software_id"], unique=False
    )
    op.create_index(op.f("ix_attack_software_stix_id"), "attack_software", ["stix_id"], unique=True)
    op.create_table(
        "attack_sync_log",
        sa.Column("domain_key", sa.String(length=20), nullable=False),
        sa.Column("domain", sa.String(length=20), nullable=False),
        sa.Column("label", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("version", sa.String(length=20), nullable=True),
        sa.Column("mitre_modified", sa.String(length=40), nullable=True),
        sa.Column("last_attempted", sa.String(length=40), nullable=True),
        sa.Column("last_sync", sa.String(length=40), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("phase", sa.String(length=30), nullable=True),
        sa.Column("bytes_downloaded", sa.BigInteger(), nullable=True),
        sa.Column("bytes_total", sa.BigInteger(), nullable=True),
        sa.Column("download_pct", sa.String(length=10), nullable=True),
        sa.Column("technique_count", sa.BigInteger(), nullable=False),
        sa.Column("tactic_count", sa.BigInteger(), nullable=False),
        sa.Column("mitigation_count", sa.BigInteger(), nullable=False),
        sa.Column("group_count", sa.BigInteger(), nullable=False),
        sa.Column("software_count", sa.BigInteger(), nullable=False),
        sa.Column("relationship_count", sa.BigInteger(), nullable=False),
        sa.Column("delta_technique_count", sa.BigInteger(), nullable=True),
        sa.Column("delta_group_count", sa.BigInteger(), nullable=True),
        sa.Column("delta_software_count", sa.BigInteger(), nullable=True),
        sa.Column("delta_mitigation_count", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("domain_key", name=op.f("pk_attack_sync_log")),
    )
    op.create_table(
        "attack_tactics",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("stix_id", sa.String(length=100), nullable=False),
        sa.Column("tactic_id", sa.String(length=20), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("shortname", sa.String(length=50), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("domains", postgresql.ARRAY(sa.String(length=20)), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attack_tactics")),
    )
    op.create_index(op.f("ix_attack_tactics_stix_id"), "attack_tactics", ["stix_id"], unique=True)
    op.create_index(
        op.f("ix_attack_tactics_tactic_id"), "attack_tactics", ["tactic_id"], unique=False
    )
    op.create_table(
        "attack_techniques",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("stix_id", sa.String(length=100), nullable=False),
        sa.Column("attack_id", sa.String(length=20), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("tactics", postgresql.ARRAY(sa.String(length=50)), nullable=False),
        sa.Column("is_subtechnique", sa.Boolean(), nullable=False),
        sa.Column("parent_id", sa.String(length=20), nullable=True),
        sa.Column("version", sa.String(length=20), nullable=False),
        sa.Column("created", sa.String(length=40), nullable=False),
        sa.Column("modified", sa.String(length=40), nullable=False),
        sa.Column("platforms", postgresql.ARRAY(sa.String(length=50)), nullable=False),
        sa.Column("data_sources", postgresql.ARRAY(sa.String(length=100)), nullable=False),
        sa.Column("detection", sa.Text(), nullable=False),
        sa.Column("domains", postgresql.ARRAY(sa.String(length=20)), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attack_techniques")),
    )
    op.create_index(
        op.f("ix_attack_techniques_attack_id"), "attack_techniques", ["attack_id"], unique=False
    )
    op.create_index(
        op.f("ix_attack_techniques_stix_id"), "attack_techniques", ["stix_id"], unique=True
    )
    op.create_table(
        "ta_profiles",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("actor_name", sa.String(length=200), nullable=False),
        sa.Column("profile", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "generated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ta_profiles")),
    )
    op.create_index(op.f("ix_ta_profiles_actor_name"), "ta_profiles", ["actor_name"], unique=True)
    op.create_table(
        "ta_whitelist",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "added_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ta_whitelist")),
    )
    op.create_index(op.f("ix_ta_whitelist_name"), "ta_whitelist", ["name"], unique=True)
    op.create_table(
        "ta_watchlist",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("client_id", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.client_id"],
            name=op.f("fk_ta_watchlist_client_id_clients"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ta_watchlist")),
    )
    op.create_index(op.f("ix_ta_watchlist_client_id"), "ta_watchlist", ["client_id"], unique=False)
    op.create_index(op.f("ix_ta_watchlist_name"), "ta_watchlist", ["name"], unique=False)
    op.create_table(
        "cve_threat_actors",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("cve_tracker_id", sa.BigInteger(), nullable=False),
        sa.Column("threat_actor", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(
            ["cve_tracker_id"],
            ["cve_tracker.id"],
            name=op.f("fk_cve_threat_actors_cve_tracker_id_cve_tracker"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cve_threat_actors")),
    )
    op.create_index(
        op.f("ix_cve_threat_actors_threat_actor"),
        "cve_threat_actors",
        ["threat_actor"],
        unique=False,
    )
    op.create_table(
        "cve_ttps",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("cve_tracker_id", sa.BigInteger(), nullable=False),
        sa.Column("ttp_id", sa.String(length=20), nullable=False),
        sa.Column("ttp_name", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(
            ["cve_tracker_id"],
            ["cve_tracker.id"],
            name=op.f("fk_cve_ttps_cve_tracker_id_cve_tracker"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cve_ttps")),
    )
    op.create_index(op.f("ix_cve_ttps_ttp_id"), "cve_ttps", ["ttp_id"], unique=False)
    # `cve_tracker` (4 baris) / `threat_actor_groups` (3992 baris) UDAH ADA
    # isinya -- kolom NOT NULL baru butuh server_default dulu biar gak
    # kena constraint violation pas ADD COLUMN, baru dicabut defaultnya
    # (baris baru wajib eksplisit ke depan) -- pola sama kayak migrasi
    # `monitored_accounts.display_name`/`notes` (Fase 7.3 Bagian 1).
    op.add_column(
        "cve_tracker",
        sa.Column("cisa_kev", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        "cve_tracker",
        sa.Column("active_exploitation", sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.alter_column("cve_tracker", "cisa_kev", server_default=None)
    op.alter_column("cve_tracker", "active_exploitation", server_default=None)
    op.add_column(
        "threat_actor_groups",
        sa.Column("source", sa.String(length=50), nullable=False, server_default="manual"),
    )
    op.alter_column("threat_actor_groups", "source", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("threat_actor_groups", "source")
    op.drop_column("cve_tracker", "active_exploitation")
    op.drop_column("cve_tracker", "cisa_kev")
    op.drop_index(op.f("ix_cve_ttps_ttp_id"), table_name="cve_ttps")
    op.drop_table("cve_ttps")
    op.drop_index(op.f("ix_cve_threat_actors_threat_actor"), table_name="cve_threat_actors")
    op.drop_table("cve_threat_actors")
    op.drop_index(op.f("ix_ta_watchlist_name"), table_name="ta_watchlist")
    op.drop_index(op.f("ix_ta_watchlist_client_id"), table_name="ta_watchlist")
    op.drop_table("ta_watchlist")
    op.drop_index(op.f("ix_ta_whitelist_name"), table_name="ta_whitelist")
    op.drop_table("ta_whitelist")
    op.drop_index(op.f("ix_ta_profiles_actor_name"), table_name="ta_profiles")
    op.drop_table("ta_profiles")
    op.drop_index(op.f("ix_attack_techniques_stix_id"), table_name="attack_techniques")
    op.drop_index(op.f("ix_attack_techniques_attack_id"), table_name="attack_techniques")
    op.drop_table("attack_techniques")
    op.drop_index(op.f("ix_attack_tactics_tactic_id"), table_name="attack_tactics")
    op.drop_index(op.f("ix_attack_tactics_stix_id"), table_name="attack_tactics")
    op.drop_table("attack_tactics")
    op.drop_table("attack_sync_log")
    op.drop_index(op.f("ix_attack_software_stix_id"), table_name="attack_software")
    op.drop_index(op.f("ix_attack_software_software_id"), table_name="attack_software")
    op.drop_table("attack_software")
    op.drop_index(op.f("ix_attack_relationships_target_ref"), table_name="attack_relationships")
    op.drop_index(op.f("ix_attack_relationships_stix_id"), table_name="attack_relationships")
    op.drop_index(op.f("ix_attack_relationships_source_ref"), table_name="attack_relationships")
    op.drop_index(op.f("ix_attack_relationships_domain"), table_name="attack_relationships")
    op.drop_table("attack_relationships")
    op.drop_index(op.f("ix_attack_mitigations_stix_id"), table_name="attack_mitigations")
    op.drop_index(op.f("ix_attack_mitigations_mitigation_id"), table_name="attack_mitigations")
    op.drop_table("attack_mitigations")
    op.drop_index(op.f("ix_attack_groups_stix_id"), table_name="attack_groups")
    op.drop_index(op.f("ix_attack_groups_group_id"), table_name="attack_groups")
    op.drop_table("attack_groups")
    # ### end Alembic commands ###
