"""fase 7.4 grup b: kolom epss/cisa-kev-detail/exploit-db di cve_tracker

Revision ID: 32dbf203b498
Revises: 0e717dcadb03
Create Date: 2026-09-19 17:16:27.413047

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "32dbf203b498"
down_revision: str | None = "0e717dcadb03"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # `server_default` di 2 kolom JSONB NOT NULL -- `cve_tracker` udah ada
    # isinya (bukan tabel baru), ALTER TABLE ADD COLUMN NOT NULL tanpa
    # default bakal gagal kena baris existing. Drop server_default-nya di
    # akhir (`alter_column`) biar model Python (`default=dict`/`default=
    # list`, level aplikasi) yang pegang kendali buat INSERT baru setelahnya
    # -- sama pola kayak kolom timestamp `server_default=now()` yang lain,
    # cuma di sini defaultnya dicopot lagi karena bukan nilai yang emang
    # mau dipertahanin selamanya di level DB.
    op.add_column("cve_tracker", sa.Column("epss_score", sa.Float(), nullable=True))
    op.add_column("cve_tracker", sa.Column("epss_percentile", sa.Float(), nullable=True))
    op.add_column("cve_tracker", sa.Column("epss_date", sa.String(length=10), nullable=True))
    op.add_column(
        "cve_tracker", sa.Column("epss_checked_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "cve_tracker", sa.Column("cisa_kev_checked_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "cve_tracker",
        sa.Column(
            "cisa_kev_detail",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'{}'::jsonb"),
            nullable=False,
        ),
    )
    op.alter_column("cve_tracker", "cisa_kev_detail", server_default=None)
    op.add_column(
        "cve_tracker", sa.Column("exploit_db_checked_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column(
        "cve_tracker",
        sa.Column(
            "exploit_db_hits",
            postgresql.JSONB(astext_type=sa.Text()),
            server_default=sa.text("'[]'::jsonb"),
            nullable=False,
        ),
    )
    op.alter_column("cve_tracker", "exploit_db_hits", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("cve_tracker", "exploit_db_hits")
    op.drop_column("cve_tracker", "exploit_db_checked_at")
    op.drop_column("cve_tracker", "cisa_kev_detail")
    op.drop_column("cve_tracker", "cisa_kev_checked_at")
    op.drop_column("cve_tracker", "epss_checked_at")
    op.drop_column("cve_tracker", "epss_date")
    op.drop_column("cve_tracker", "epss_percentile")
    op.drop_column("cve_tracker", "epss_score")
    # ### end Alembic commands ###
