"""fase 7 bagian 4: rombak skema pkg_vuln (monitored_packages, package_vulns, package_dep_graphs)

Revision ID: 40ec5ab42f56
Revises: d5eeecc065b0
Create Date: 2026-09-19 09:01:11.874887

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "40ec5ab42f56"
down_revision: str | None = "d5eeecc065b0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "package_dep_graphs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("pkg_id", sa.BigInteger(), nullable=False),
        sa.Column("package_name", sa.String(length=300), nullable=False),
        sa.Column("ecosystem", sa.String(length=30), nullable=False),
        sa.Column("version", sa.String(length=200), nullable=True),
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("direct_count", sa.Integer(), nullable=False),
        sa.Column("indirect_count", sa.Integer(), nullable=False),
        sa.Column("total_count", sa.Integer(), nullable=False),
        sa.Column("direct_deps", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("indirect_deps", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("scorecard_score", sa.Float(), nullable=True),
        sa.Column("scorecard_date", sa.String(length=10), nullable=True),
        sa.Column("scorecard_project", sa.String(length=300), nullable=True),
        sa.Column("scorecard_checks", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pkg_id"],
            ["monitored_packages.id"],
            name=op.f("fk_package_dep_graphs_pkg_id_monitored_packages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_package_dep_graphs")),
        sa.UniqueConstraint("pkg_id", name=op.f("uq_package_dep_graphs_pkg_id")),
    )
    op.drop_table("package_vuln_aliases")
    op.drop_table("package_dep_edges")
    op.add_column("monitored_packages", sa.Column("added_date", sa.Date(), nullable=False))
    op.add_column("monitored_packages", sa.Column("source", sa.String(length=20), nullable=False))
    op.add_column(
        "monitored_packages", sa.Column("last_scan", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("monitored_packages", sa.Column("vuln_count", sa.Integer(), nullable=False))
    op.add_column("monitored_packages", sa.Column("critical_count", sa.Integer(), nullable=False))
    op.add_column("monitored_packages", sa.Column("high_count", sa.Integer(), nullable=False))
    op.add_column("monitored_packages", sa.Column("medium_count", sa.Integer(), nullable=False))
    op.add_column("monitored_packages", sa.Column("low_count", sa.Integer(), nullable=False))
    op.add_column(
        "monitored_packages", sa.Column("highest_severity", sa.String(length=10), nullable=False)
    )
    op.add_column(
        "monitored_packages", sa.Column("latest_version", sa.String(length=200), nullable=True)
    )
    op.add_column("monitored_packages", sa.Column("dep_direct_count", sa.Integer(), nullable=False))
    op.add_column(
        "monitored_packages", sa.Column("dep_indirect_count", sa.Integer(), nullable=False)
    )
    op.add_column("monitored_packages", sa.Column("dep_total_count", sa.Integer(), nullable=False))
    op.add_column(
        "monitored_packages",
        sa.Column("dep_resolved_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column("monitored_packages", sa.Column("scorecard_score", sa.Float(), nullable=True))
    op.add_column(
        "monitored_packages", sa.Column("scorecard_date", sa.String(length=10), nullable=True)
    )
    op.alter_column(
        "monitored_packages",
        "version",
        existing_type=sa.VARCHAR(length=100),
        type_=sa.String(length=200),
        existing_nullable=True,
    )
    op.add_column("package_vulns", sa.Column("package_name", sa.String(length=300), nullable=False))
    op.add_column("package_vulns", sa.Column("ecosystem", sa.String(length=30), nullable=False))
    op.add_column(
        "package_vulns", sa.Column("pinned_version", sa.String(length=200), nullable=True)
    )
    op.add_column("package_vulns", sa.Column("advisory_id", sa.String(length=100), nullable=False))
    op.add_column(
        "package_vulns",
        sa.Column("aliases", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    )
    op.add_column("package_vulns", sa.Column("summary", sa.Text(), nullable=False))
    op.add_column("package_vulns", sa.Column("details", sa.Text(), nullable=False))
    op.add_column("package_vulns", sa.Column("cvss_score", sa.Float(), nullable=True))
    op.add_column("package_vulns", sa.Column("epss_score", sa.Float(), nullable=True))
    op.add_column("package_vulns", sa.Column("epss_percentile", sa.Float(), nullable=True))
    op.add_column("package_vulns", sa.Column("kev_date_added", sa.String(length=10), nullable=True))
    op.add_column("package_vulns", sa.Column("adjusted_score", sa.Float(), nullable=True))
    op.add_column("package_vulns", sa.Column("published", sa.Date(), nullable=True))
    op.add_column("package_vulns", sa.Column("modified", sa.Date(), nullable=True))
    op.add_column("package_vulns", sa.Column("fixed_version", sa.String(length=200), nullable=True))
    op.add_column(
        "package_vulns",
        sa.Column(
            "affected_version_ranges", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
    )
    op.add_column(
        "package_vulns",
        sa.Column("references", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    )
    op.add_column("package_vulns", sa.Column("client_id", sa.String(length=50), nullable=False))
    op.add_column("package_vulns", sa.Column("ack_by", sa.String(length=200), nullable=True))
    op.add_column("package_vulns", sa.Column("ack_date", sa.DateTime(timezone=True), nullable=True))
    op.add_column("package_vulns", sa.Column("source", sa.String(length=20), nullable=False))
    op.add_column(
        "package_vulns", sa.Column("last_updated", sa.DateTime(timezone=True), nullable=False)
    )
    op.alter_column(
        "package_vulns",
        "severity",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=10),
        nullable=False,
    )
    op.alter_column(
        "package_vulns",
        "adjusted_severity",
        existing_type=sa.VARCHAR(length=20),
        type_=sa.String(length=10),
        existing_nullable=True,
    )
    op.drop_index(op.f("ix_package_vulns_vuln_id"), table_name="package_vulns")
    op.drop_constraint(op.f("uq_package_vuln"), "package_vulns", type_="unique")
    op.create_unique_constraint(
        "uq_package_vuln",
        "package_vulns",
        ["package_name", "ecosystem", "advisory_id", "client_id"],
    )
    op.create_index(
        op.f("ix_package_vulns_client_id"), "package_vulns", ["client_id"], unique=False
    )
    op.create_index(
        op.f("ix_package_vulns_package_name"), "package_vulns", ["package_name"], unique=False
    )
    op.drop_constraint(
        op.f("fk_package_vulns_monitored_package_id_monitored_packages"),
        "package_vulns",
        type_="foreignkey",
    )
    op.create_foreign_key(
        op.f("fk_package_vulns_client_id_clients"),
        "package_vulns",
        "clients",
        ["client_id"],
        ["client_id"],
        ondelete="CASCADE",
    )
    op.drop_column("package_vulns", "monitored_package_id")
    op.drop_column("package_vulns", "vuln_id")
    op.drop_column("package_vulns", "epss")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "package_vulns",
        sa.Column("epss", sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    )
    op.add_column(
        "package_vulns",
        sa.Column("vuln_id", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    )
    op.add_column(
        "package_vulns",
        sa.Column("monitored_package_id", sa.BIGINT(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(
        op.f("fk_package_vulns_client_id_clients"), "package_vulns", type_="foreignkey"
    )
    op.create_foreign_key(
        op.f("fk_package_vulns_monitored_package_id_monitored_packages"),
        "package_vulns",
        "monitored_packages",
        ["monitored_package_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index(op.f("ix_package_vulns_package_name"), table_name="package_vulns")
    op.drop_index(op.f("ix_package_vulns_client_id"), table_name="package_vulns")
    op.drop_constraint("uq_package_vuln", "package_vulns", type_="unique")
    op.create_unique_constraint(
        op.f("uq_package_vuln"),
        "package_vulns",
        ["monitored_package_id", "vuln_id"],
        postgresql_nulls_not_distinct=False,
    )
    op.create_index(op.f("ix_package_vulns_vuln_id"), "package_vulns", ["vuln_id"], unique=False)
    op.alter_column(
        "package_vulns",
        "adjusted_severity",
        existing_type=sa.String(length=10),
        type_=sa.VARCHAR(length=20),
        existing_nullable=True,
    )
    op.alter_column(
        "package_vulns",
        "severity",
        existing_type=sa.String(length=10),
        type_=sa.VARCHAR(length=20),
        nullable=True,
    )
    op.drop_column("package_vulns", "last_updated")
    op.drop_column("package_vulns", "source")
    op.drop_column("package_vulns", "ack_date")
    op.drop_column("package_vulns", "ack_by")
    op.drop_column("package_vulns", "client_id")
    op.drop_column("package_vulns", "references")
    op.drop_column("package_vulns", "affected_version_ranges")
    op.drop_column("package_vulns", "fixed_version")
    op.drop_column("package_vulns", "modified")
    op.drop_column("package_vulns", "published")
    op.drop_column("package_vulns", "adjusted_score")
    op.drop_column("package_vulns", "kev_date_added")
    op.drop_column("package_vulns", "epss_percentile")
    op.drop_column("package_vulns", "epss_score")
    op.drop_column("package_vulns", "cvss_score")
    op.drop_column("package_vulns", "details")
    op.drop_column("package_vulns", "summary")
    op.drop_column("package_vulns", "aliases")
    op.drop_column("package_vulns", "advisory_id")
    op.drop_column("package_vulns", "pinned_version")
    op.drop_column("package_vulns", "ecosystem")
    op.drop_column("package_vulns", "package_name")
    op.alter_column(
        "monitored_packages",
        "version",
        existing_type=sa.String(length=200),
        type_=sa.VARCHAR(length=100),
        existing_nullable=True,
    )
    op.drop_column("monitored_packages", "scorecard_date")
    op.drop_column("monitored_packages", "scorecard_score")
    op.drop_column("monitored_packages", "dep_resolved_at")
    op.drop_column("monitored_packages", "dep_total_count")
    op.drop_column("monitored_packages", "dep_indirect_count")
    op.drop_column("monitored_packages", "dep_direct_count")
    op.drop_column("monitored_packages", "latest_version")
    op.drop_column("monitored_packages", "highest_severity")
    op.drop_column("monitored_packages", "low_count")
    op.drop_column("monitored_packages", "medium_count")
    op.drop_column("monitored_packages", "high_count")
    op.drop_column("monitored_packages", "critical_count")
    op.drop_column("monitored_packages", "vuln_count")
    op.drop_column("monitored_packages", "last_scan")
    op.drop_column("monitored_packages", "source")
    op.drop_column("monitored_packages", "added_date")
    op.create_table(
        "package_dep_edges",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("monitored_package_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("depends_on", sa.VARCHAR(length=300), autoincrement=False, nullable=False),
        sa.Column(
            "depends_on_ecosystem", sa.VARCHAR(length=30), autoincrement=False, nullable=False
        ),
        sa.Column("depends_on_version", sa.VARCHAR(length=100), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["monitored_package_id"],
            ["monitored_packages.id"],
            name=op.f("fk_package_dep_edges_monitored_package_id_monitored_packages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_package_dep_edges")),
        sa.UniqueConstraint(
            "monitored_package_id",
            "depends_on",
            "depends_on_ecosystem",
            name=op.f("uq_package_dep_edge"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_table(
        "package_vuln_aliases",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("package_vuln_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("alias", sa.VARCHAR(length=50), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["package_vuln_id"],
            ["package_vulns.id"],
            name=op.f("fk_package_vuln_aliases_package_vuln_id_package_vulns"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_package_vuln_aliases")),
        sa.UniqueConstraint(
            "package_vuln_id",
            "alias",
            name=op.f("uq_package_vuln_alias"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.drop_table("package_dep_graphs")
    # ### end Alembic commands ###
