"""fase_7_4_grup_c_rombak_skema_cve_tickets

Revision ID: 528b8e6665cf
Revises: 20e63ec867dd
Create Date: 2026-09-23 13:57:12.927522

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "528b8e6665cf"
down_revision: str | None = "20e63ec867dd"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_cve_ticket_items_cve_id"), table_name="cve_ticket_items")
    op.drop_table("cve_ticket_items")
    op.add_column("cve_tickets", sa.Column("cve_id", sa.String(length=20), nullable=False))
    op.add_column("cve_tickets", sa.Column("client_id", sa.String(length=50), nullable=False))
    op.add_column("cve_tickets", sa.Column("affected_asset", sa.Text(), nullable=True))
    op.add_column("cve_tickets", sa.Column("affected_version", sa.Text(), nullable=True))
    op.add_column("cve_tickets", sa.Column("fixed_version", sa.Text(), nullable=True))
    op.add_column("cve_tickets", sa.Column("asset_owner", sa.String(length=200), nullable=True))
    op.add_column("cve_tickets", sa.Column("owner_email", sa.String(length=200), nullable=True))
    op.add_column("cve_tickets", sa.Column("owner_team", sa.String(length=200), nullable=True))
    op.add_column(
        "cve_tickets", sa.Column("active_exploitation", sa.String(length=50), nullable=True)
    )
    op.add_column("cve_tickets", sa.Column("remediation_date_plan", sa.Date(), nullable=True))
    op.add_column(
        "cve_tickets", sa.Column("remediation_status", sa.String(length=50), nullable=True)
    )
    op.add_column("cve_tickets", sa.Column("actual_remediation_date", sa.Date(), nullable=True))
    op.add_column("cve_tickets", sa.Column("escalation_required", sa.Boolean(), nullable=False))
    op.add_column("cve_tickets", sa.Column("comments", sa.Text(), nullable=True))
    op.add_column("cve_tickets", sa.Column("risk_acceptance", sa.String(length=50), nullable=True))
    op.add_column("cve_tickets", sa.Column("closure_date", sa.Date(), nullable=True))
    op.add_column("cve_tickets", sa.Column("acknowledged_by", sa.String(length=200), nullable=True))
    op.add_column(
        "cve_tickets", sa.Column("acknowledge_time", sa.DateTime(timezone=True), nullable=True)
    )
    op.create_index(op.f("ix_cve_tickets_client_id"), "cve_tickets", ["client_id"], unique=False)
    op.create_index(op.f("ix_cve_tickets_cve_id"), "cve_tickets", ["cve_id"], unique=False)
    op.create_unique_constraint("uq_cve_tickets_cve_client", "cve_tickets", ["cve_id", "client_id"])
    op.create_foreign_key(
        op.f("fk_cve_tickets_client_id_clients"),
        "cve_tickets",
        "clients",
        ["client_id"],
        ["client_id"],
        ondelete="CASCADE",
    )
    op.drop_column("cve_tickets", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "cve_tickets",
        sa.Column("status", sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    )
    op.drop_constraint(op.f("fk_cve_tickets_client_id_clients"), "cve_tickets", type_="foreignkey")
    op.drop_constraint("uq_cve_tickets_cve_client", "cve_tickets", type_="unique")
    op.drop_index(op.f("ix_cve_tickets_cve_id"), table_name="cve_tickets")
    op.drop_index(op.f("ix_cve_tickets_client_id"), table_name="cve_tickets")
    op.drop_column("cve_tickets", "acknowledge_time")
    op.drop_column("cve_tickets", "acknowledged_by")
    op.drop_column("cve_tickets", "closure_date")
    op.drop_column("cve_tickets", "risk_acceptance")
    op.drop_column("cve_tickets", "comments")
    op.drop_column("cve_tickets", "escalation_required")
    op.drop_column("cve_tickets", "actual_remediation_date")
    op.drop_column("cve_tickets", "remediation_status")
    op.drop_column("cve_tickets", "remediation_date_plan")
    op.drop_column("cve_tickets", "active_exploitation")
    op.drop_column("cve_tickets", "owner_team")
    op.drop_column("cve_tickets", "owner_email")
    op.drop_column("cve_tickets", "asset_owner")
    op.drop_column("cve_tickets", "fixed_version")
    op.drop_column("cve_tickets", "affected_version")
    op.drop_column("cve_tickets", "affected_asset")
    op.drop_column("cve_tickets", "client_id")
    op.drop_column("cve_tickets", "cve_id")
    op.create_table(
        "cve_ticket_items",
        sa.Column("id", sa.BIGINT(), autoincrement=True, nullable=False),
        sa.Column("ticket_id", sa.BIGINT(), autoincrement=False, nullable=False),
        sa.Column("cve_id", sa.VARCHAR(length=20), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["cve_tickets.id"],
            name=op.f("fk_cve_ticket_items_ticket_id_cve_tickets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cve_ticket_items")),
        sa.UniqueConstraint(
            "ticket_id",
            "cve_id",
            name=op.f("uq_cve_ticket_item"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("ix_cve_ticket_items_cve_id"), "cve_ticket_items", ["cve_id"], unique=False
    )
    # ### end Alembic commands ###
