"""fase 7: role display_name/created_by, audit target_id, password_policies

Revision ID: 5a456e9251a0
Revises: a6f893e1319d
Create Date: 2026-09-18 17:38:45.571626

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5a456e9251a0"
down_revision: str | None = "a6f893e1319d"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "password_policies",
        sa.Column("id", sa.BigInteger(), nullable=False),
        sa.Column("min_length", sa.Integer(), nullable=False),
        sa.Column("require_upper", sa.Boolean(), nullable=False),
        sa.Column("require_lower", sa.Boolean(), nullable=False),
        sa.Column("require_number", sa.Boolean(), nullable=False),
        sa.Column("require_symbol", sa.Boolean(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_password_policies")),
    )
    op.add_column("audit_log", sa.Column("target_id", sa.String(length=200), nullable=False))
    op.add_column("roles", sa.Column("display_name", sa.String(length=100), nullable=False))
    op.add_column("roles", sa.Column("created_by", sa.String(length=200), nullable=False))
    op.add_column(
        "roles",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    op.add_column(
        "roles",
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("roles", "updated_at")
    op.drop_column("roles", "created_at")
    op.drop_column("roles", "created_by")
    op.drop_column("roles", "display_name")
    op.drop_column("audit_log", "target_id")
    op.drop_table("password_policies")
    # ### end Alembic commands ###
