"""fase_5_ioc_allowlist_threat_feed_group_reference

Revision ID: 5b7fe9a443b8
Revises: 21d5ede00400
Create Date: 2026-09-17 18:57:30.371410

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5b7fe9a443b8"
down_revision: str | None = "21d5ede00400"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ioc_allowlist_entries",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("value", sa.String(length=300), nullable=False),
        sa.Column("note", sa.String(length=300), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ioc_allowlist_entries")),
        sa.UniqueConstraint("type", "value", name="uq_ioc_allowlist_type_value"),
    )
    op.create_index(
        op.f("ix_ioc_allowlist_entries_type"), "ioc_allowlist_entries", ["type"], unique=False
    )
    op.create_table(
        "monitored_people",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_monitored_people")),
        sa.UniqueConstraint("name", name="uq_monitored_person_name"),
    )
    op.create_index(op.f("ix_monitored_people_name"), "monitored_people", ["name"], unique=False)
    op.create_table(
        "threat_actor_groups",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_threat_actor_groups")),
        sa.UniqueConstraint("name", name="uq_threat_actor_group_name"),
    )
    op.create_index(
        op.f("ix_threat_actor_groups_name"), "threat_actor_groups", ["name"], unique=False
    )
    op.create_table(
        "threat_feed_entries",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("feed", sa.String(length=50), nullable=False),
        sa.Column("type", sa.String(length=10), nullable=False),
        sa.Column("value", sa.String(length=300), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_threat_feed_entries")),
        sa.UniqueConstraint("feed", "type", "value", name="uq_threat_feed_entry"),
    )
    op.create_index(
        op.f("ix_threat_feed_entries_feed"), "threat_feed_entries", ["feed"], unique=False
    )
    op.create_index(
        op.f("ix_threat_feed_entries_value"), "threat_feed_entries", ["value"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_threat_feed_entries_value"), table_name="threat_feed_entries")
    op.drop_index(op.f("ix_threat_feed_entries_feed"), table_name="threat_feed_entries")
    op.drop_table("threat_feed_entries")
    op.drop_index(op.f("ix_threat_actor_groups_name"), table_name="threat_actor_groups")
    op.drop_table("threat_actor_groups")
    op.drop_index(op.f("ix_monitored_people_name"), table_name="monitored_people")
    op.drop_table("monitored_people")
    op.drop_index(op.f("ix_ioc_allowlist_entries_type"), table_name="ioc_allowlist_entries")
    op.drop_table("ioc_allowlist_entries")
    # ### end Alembic commands ###
