"""fase_7_4_grup_a_tabel_clusters

Revision ID: 6e5de9ec8b9b
Revises: 528b8e6665cf
Create Date: 2026-09-23 17:54:56.784222

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6e5de9ec8b9b"
down_revision: str | None = "528b8e6665cf"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "clusters",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("cluster_id", sa.String(length=20), nullable=False),
        sa.Column("cluster_name", sa.Text(), nullable=False),
        sa.Column("first_seen", sa.Date(), nullable=False),
        sa.Column("last_seen", sa.Date(), nullable=False),
        sa.Column("last_count", sa.Integer(), nullable=False),
        sa.Column("peak_count", sa.Integer(), nullable=False),
        sa.Column("daily_counts", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_clusters")),
    )
    op.create_index(op.f("ix_clusters_cluster_id"), "clusters", ["cluster_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_clusters_cluster_id"), table_name="clusters")
    op.drop_table("clusters")
    # ### end Alembic commands ###
