"""fase 7: tabel rejected_articles buat filtered_articles

Revision ID: 8c208279c67f
Revises: 22b43affdcac
Create Date: 2026-09-18 19:26:08.111718

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8c208279c67f"
down_revision: str | None = "22b43affdcac"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rejected_articles",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("url_hash", sa.String(length=64), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=200), nullable=False),
        sa.Column("scraper_id", sa.String(length=100), nullable=True),
        sa.Column("posted_on", sa.Date(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column(
            "rejected_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rejected_articles")),
        sa.UniqueConstraint("url_hash", name="uq_rejected_articles_url_hash"),
    )
    op.create_index(
        op.f("ix_rejected_articles_scraper_id"), "rejected_articles", ["scraper_id"], unique=False
    )
    op.create_index(
        op.f("ix_rejected_articles_source"), "rejected_articles", ["source"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rejected_articles_source"), table_name="rejected_articles")
    op.drop_index(op.f("ix_rejected_articles_scraper_id"), table_name="rejected_articles")
    op.drop_table("rejected_articles")
    # ### end Alembic commands ###
