"""skema awal fase 2

Revision ID: 95d44de9a462
Revises:
Create Date: 2026-09-17 08:44:29.522931

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "95d44de9a462"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "articles",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("url_hash", sa.String(length=64), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=200), nullable=False),
        sa.Column("posted_on", sa.Date(), nullable=True),
        sa.Column("scraper_id", sa.String(length=100), nullable=True),
        sa.Column("news_type", sa.String(length=50), nullable=True),
        sa.Column("confidence_score", sa.SmallInteger(), nullable=True),
        sa.Column("confirmed_incident", sa.Boolean(), nullable=False),
        sa.Column("incident_confidence", sa.SmallInteger(), nullable=True),
        sa.Column("victim_name", sa.String(length=300), nullable=True),
        sa.Column("c2_indicator", sa.Boolean(), nullable=False),
        sa.Column("seen_count", sa.Integer(), nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("raw_enrichment", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("overrides", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("schema_version", sa.SmallInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_articles")),
        sa.UniqueConstraint("url_hash", name=op.f("uq_articles_url_hash")),
    )
    op.create_index(op.f("ix_articles_news_type"), "articles", ["news_type"], unique=False)
    op.create_index(op.f("ix_articles_scraper_id"), "articles", ["scraper_id"], unique=False)
    op.create_index(op.f("ix_articles_source"), "articles", ["source"], unique=False)
    op.create_table(
        "audit_log",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=200), nullable=False),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("detail", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column(
            "at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_log")),
    )
    op.create_index(op.f("ix_audit_log_action"), "audit_log", ["action"], unique=False)
    op.create_index(op.f("ix_audit_log_at"), "audit_log", ["at"], unique=False)
    op.create_index(op.f("ix_audit_log_username"), "audit_log", ["username"], unique=False)
    op.create_table(
        "clients",
        sa.Column("client_id", sa.String(length=50), nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("client_id", name=op.f("pk_clients")),
    )
    op.create_table(
        "cve_tickets",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ticket_id", sa.String(length=50), nullable=False),
        sa.Column("status", sa.String(length=30), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cve_tickets")),
    )
    op.create_index(op.f("ix_cve_tickets_ticket_id"), "cve_tickets", ["ticket_id"], unique=True)
    op.create_table(
        "iocs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("type", sa.String(length=20), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "last_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("seen_count", sa.Integer(), nullable=False),
        sa.Column("confidence_score", sa.SmallInteger(), nullable=False),
        sa.Column("confidence_decayed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tp_count", sa.Integer(), nullable=False),
        sa.Column("fp_count", sa.Integer(), nullable=False),
        sa.Column("auto_suppressed", sa.Boolean(), nullable=False),
        sa.Column("suppression_reason", sa.Text(), nullable=True),
        sa.Column("enrichment", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_iocs")),
        sa.UniqueConstraint("type", "value", name="uq_iocs_type_value"),
    )
    op.create_index(op.f("ix_iocs_type"), "iocs", ["type"], unique=False)
    op.create_table(
        "monitored_accounts",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("active", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_monitored_accounts")),
    )
    op.create_index(
        op.f("ix_monitored_accounts_username"), "monitored_accounts", ["username"], unique=True
    )
    op.create_table(
        "ransomware_victims",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("offset_key", sa.String(length=600), nullable=False),
        sa.Column("group_name", sa.String(length=200), nullable=False),
        sa.Column("victim", sa.String(length=500), nullable=False),
        sa.Column("domain", sa.String(length=300), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("country_code", sa.String(length=2), nullable=True),
        sa.Column("industry", sa.String(length=150), nullable=True),
        sa.Column("published", sa.Date(), nullable=True),
        sa.Column("discovered", sa.Date(), nullable=True),
        sa.Column("post_url", sa.Text(), nullable=False),
        sa.Column("ransom", sa.Text(), nullable=True),
        sa.Column("data_size", sa.Text(), nullable=True),
        sa.Column("screenshot", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ransomware_victims")),
        sa.UniqueConstraint("offset_key", name="uq_ransomware_offset_key"),
    )
    op.create_index(
        op.f("ix_ransomware_victims_country_code"),
        "ransomware_victims",
        ["country_code"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ransomware_victims_group_name"), "ransomware_victims", ["group_name"], unique=False
    )
    op.create_table(
        "roles",
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.Column("permissions", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("is_system", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("name", name=op.f("pk_roles")),
    )
    op.create_table(
        "scraper_config",
        sa.Column("scraper_id", sa.String(length=100), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("schedule", sa.String(length=100), nullable=True),
        sa.Column("rate_limit", sa.String(length=30), nullable=True),
        sa.Column("max_items", sa.Integer(), nullable=True),
        sa.Column("paused_reason", sa.Text(), nullable=True),
        sa.Column("updated_by", sa.String(length=200), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("scraper_id", name=op.f("pk_scraper_config")),
    )
    op.create_table(
        "scraper_runs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=30), nullable=False),
        sa.Column("scraper_id", sa.String(length=100), nullable=False),
        sa.Column("trigger", sa.String(length=20), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column(
            "started_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("items_found", sa.Integer(), nullable=False),
        sa.Column("items_new", sa.Integer(), nullable=False),
        sa.Column("items_dropped", sa.Integer(), nullable=False),
        sa.Column("items_failed", sa.Integer(), nullable=False),
        sa.Column("errors", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("celery_task_id", sa.String(length=50), nullable=True),
        sa.Column("worker", sa.String(length=100), nullable=True),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scraper_runs")),
    )
    op.create_index(op.f("ix_scraper_runs_run_id"), "scraper_runs", ["run_id"], unique=True)
    op.create_index(
        op.f("ix_scraper_runs_scraper_id"), "scraper_runs", ["scraper_id"], unique=False
    )
    op.create_index(op.f("ix_scraper_runs_status"), "scraper_runs", ["status"], unique=False)
    op.create_table(
        "scraper_seen",
        sa.Column("dedup_key", sa.String(length=64), nullable=False),
        sa.Column("scraper_id", sa.String(length=100), nullable=False),
        sa.Column("state", sa.String(length=20), nullable=False),
        sa.Column("lease_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("poisoned", sa.Boolean(), nullable=False),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("committed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expire_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("dedup_key", name=op.f("pk_scraper_seen")),
    )
    op.create_index(op.f("ix_scraper_seen_expire_at"), "scraper_seen", ["expire_at"], unique=False)
    op.create_index(
        op.f("ix_scraper_seen_scraper_id"), "scraper_seen", ["scraper_id"], unique=False
    )
    op.create_table(
        "tweets",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("tweet_id", sa.String(length=50), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("author_username", sa.String(length=100), nullable=False),
        sa.Column("author_name", sa.String(length=200), nullable=True),
        sa.Column("author_avatar", sa.Text(), nullable=True),
        sa.Column("author_followers", sa.Integer(), nullable=True),
        sa.Column("posted_on", sa.DateTime(timezone=True), nullable=True),
        sa.Column("lang", sa.String(length=10), nullable=True),
        sa.Column("media_urls", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "fetched_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("scan_results", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("confidence_score", sa.SmallInteger(), nullable=True),
        sa.Column("confirmed_incident", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tweets")),
    )
    op.create_index(op.f("ix_tweets_author_username"), "tweets", ["author_username"], unique=False)
    op.create_index(op.f("ix_tweets_tweet_id"), "tweets", ["tweet_id"], unique=True)
    op.create_table(
        "article_countries",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.Column("role", sa.String(length=10), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
            name=op.f("fk_article_countries_article_id_articles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_article_countries")),
        sa.UniqueConstraint("article_id", "country_code", "role", name="uq_article_country_role"),
    )
    op.create_index(
        "ix_article_countries_country_role",
        "article_countries",
        ["country_code", "role"],
        unique=False,
    )
    op.create_table(
        "article_industries",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column("industry", sa.String(length=150), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
            name=op.f("fk_article_industries_article_id_articles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_article_industries")),
        sa.UniqueConstraint("article_id", "industry", name="uq_article_industry"),
    )
    op.create_index(
        op.f("ix_article_industries_industry"), "article_industries", ["industry"], unique=False
    )
    op.create_table(
        "article_threat_actors",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column("threat_actor", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
            name=op.f("fk_article_threat_actors_article_id_articles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_article_threat_actors")),
        sa.UniqueConstraint("article_id", "threat_actor", name="uq_article_threat_actor"),
    )
    op.create_index(
        op.f("ix_article_threat_actors_threat_actor"),
        "article_threat_actors",
        ["threat_actor"],
        unique=False,
    )
    op.create_table(
        "article_ttps",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("article_id", sa.BigInteger(), nullable=False),
        sa.Column("ttp_id", sa.String(length=20), nullable=False),
        sa.Column("ttp_name", sa.String(length=300), nullable=False),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
            name=op.f("fk_article_ttps_article_id_articles"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_article_ttps")),
        sa.UniqueConstraint("article_id", "ttp_id", name="uq_article_ttp"),
    )
    op.create_index(op.f("ix_article_ttps_ttp_id"), "article_ttps", ["ttp_id"], unique=False)
    op.create_table(
        "client_countries",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("client_id", sa.String(length=50), nullable=False),
        sa.Column("country_code", sa.String(length=2), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.client_id"],
            name=op.f("fk_client_countries_client_id_clients"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_client_countries")),
        sa.UniqueConstraint("client_id", "country_code", name="uq_client_country"),
    )
    op.create_table(
        "cve_false_positives",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("cve_id", sa.String(length=20), nullable=False),
        sa.Column("client_id", sa.String(length=50), nullable=False),
        sa.Column("marked_by", sa.String(length=200), nullable=True),
        sa.Column(
            "marked_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.client_id"],
            name=op.f("fk_cve_false_positives_client_id_clients"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cve_false_positives")),
        sa.UniqueConstraint("cve_id", "client_id", name="uq_cve_fp_cve_client"),
    )
    op.create_index(
        op.f("ix_cve_false_positives_cve_id"), "cve_false_positives", ["cve_id"], unique=False
    )
    op.create_table(
        "cve_ticket_items",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ticket_id", sa.BigInteger(), nullable=False),
        sa.Column("cve_id", sa.String(length=20), nullable=False),
        sa.ForeignKeyConstraint(
            ["ticket_id"],
            ["cve_tickets.id"],
            name=op.f("fk_cve_ticket_items_ticket_id_cve_tickets"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cve_ticket_items")),
        sa.UniqueConstraint("ticket_id", "cve_id", name="uq_cve_ticket_item"),
    )
    op.create_index(
        op.f("ix_cve_ticket_items_cve_id"), "cve_ticket_items", ["cve_id"], unique=False
    )
    op.create_table(
        "cve_tracker",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("cve_id", sa.String(length=20), nullable=False),
        sa.Column("client_id", sa.String(length=50), nullable=False),
        sa.Column("tech", sa.String(length=200), nullable=True),
        sa.Column("link", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("published", sa.Date(), nullable=True),
        sa.Column("solutions", sa.Text(), nullable=True),
        sa.Column("cve_score", sa.Float(), nullable=True),
        sa.Column("cve_severity", sa.String(length=20), nullable=True),
        sa.Column("cvss_vector", sa.String(length=100), nullable=True),
        sa.Column("cve_modified_date", sa.Date(), nullable=True),
        sa.Column("poc_available", sa.Boolean(), nullable=False),
        sa.Column(
            "detected_on",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("registered_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.client_id"],
            name=op.f("fk_cve_tracker_client_id_clients"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cve_tracker")),
        sa.UniqueConstraint("cve_id", "client_id", name="uq_cve_tracker_cve_client"),
    )
    op.create_index(op.f("ix_cve_tracker_client_id"), "cve_tracker", ["client_id"], unique=False)
    op.create_index(op.f("ix_cve_tracker_cve_id"), "cve_tracker", ["cve_id"], unique=False)
    op.create_table(
        "ioc_feedback",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ioc_id", sa.BigInteger(), nullable=False),
        sa.Column("verdict", sa.String(length=2), nullable=False),
        sa.Column("submitted_by", sa.String(length=200), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column(
            "submitted_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["ioc_id"], ["iocs.id"], name=op.f("fk_ioc_feedback_ioc_id_iocs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ioc_feedback")),
    )
    op.create_table(
        "ioc_sources",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ioc_id", sa.BigInteger(), nullable=False),
        sa.Column("article_id", sa.BigInteger(), nullable=True),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("source_name", sa.String(length=200), nullable=False),
        sa.Column("context", sa.Text(), nullable=True),
        sa.Column(
            "first_seen_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["article_id"],
            ["articles.id"],
            name=op.f("fk_ioc_sources_article_id_articles"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["ioc_id"], ["iocs.id"], name=op.f("fk_ioc_sources_ioc_id_iocs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ioc_sources")),
    )
    op.create_table(
        "ioc_tags",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ioc_id", sa.BigInteger(), nullable=False),
        sa.Column("tag", sa.String(length=100), nullable=False),
        sa.ForeignKeyConstraint(
            ["ioc_id"], ["iocs.id"], name=op.f("fk_ioc_tags_ioc_id_iocs"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ioc_tags")),
        sa.UniqueConstraint("ioc_id", "tag", name="uq_ioc_tag"),
    )
    op.create_index(op.f("ix_ioc_tags_tag"), "ioc_tags", ["tag"], unique=False)
    op.create_table(
        "ioc_threat_actors",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ioc_id", sa.BigInteger(), nullable=False),
        sa.Column("threat_actor", sa.String(length=200), nullable=False),
        sa.ForeignKeyConstraint(
            ["ioc_id"],
            ["iocs.id"],
            name=op.f("fk_ioc_threat_actors_ioc_id_iocs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ioc_threat_actors")),
        sa.UniqueConstraint("ioc_id", "threat_actor", name="uq_ioc_threat_actor"),
    )
    op.create_index(
        op.f("ix_ioc_threat_actors_threat_actor"),
        "ioc_threat_actors",
        ["threat_actor"],
        unique=False,
    )
    op.create_table(
        "monitored_packages",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("ecosystem", sa.String(length=30), nullable=False),
        sa.Column("version", sa.String(length=100), nullable=True),
        sa.Column("client_id", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.client_id"],
            name=op.f("fk_monitored_packages_client_id_clients"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_monitored_packages")),
        sa.UniqueConstraint("name", "ecosystem", "client_id", name="uq_monitored_package"),
    )
    op.create_index(
        op.f("ix_monitored_packages_client_id"), "monitored_packages", ["client_id"], unique=False
    )
    op.create_index(
        op.f("ix_monitored_packages_name"), "monitored_packages", ["name"], unique=False
    )
    op.create_table(
        "scraper_items",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("run_id", sa.String(length=30), nullable=False),
        sa.Column("scraper_id", sa.String(length=100), nullable=False),
        sa.Column("url_hash", sa.String(length=64), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("accepted", sa.Boolean(), nullable=False),
        sa.Column("reason", sa.String(length=200), nullable=True),
        sa.Column("legacy_script_label", sa.String(length=200), nullable=True),
        sa.Column(
            "run_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["scraper_runs.run_id"],
            name=op.f("fk_scraper_items_run_id_scraper_runs"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_scraper_items")),
    )
    op.create_index(op.f("ix_scraper_items_run_at"), "scraper_items", ["run_at"], unique=False)
    op.create_index(op.f("ix_scraper_items_run_id"), "scraper_items", ["run_id"], unique=False)
    op.create_index(
        op.f("ix_scraper_items_scraper_id"), "scraper_items", ["scraper_id"], unique=False
    )
    op.create_table(
        "techstack_entries",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=200), nullable=False),
        sa.Column("client_id", sa.String(length=50), nullable=False),
        sa.Column("exposure", sa.String(length=50), nullable=True),
        sa.Column("hosting_type", sa.String(length=50), nullable=True),
        sa.Column("source", sa.String(length=100), nullable=True),
        sa.Column("added_date", sa.Date(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.client_id"],
            name=op.f("fk_techstack_entries_client_id_clients"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_techstack_entries")),
        sa.UniqueConstraint("name", "client_id", name="uq_techstack_name_client"),
    )
    op.create_index(
        op.f("ix_techstack_entries_client_id"), "techstack_entries", ["client_id"], unique=False
    )
    op.create_index(op.f("ix_techstack_entries_name"), "techstack_entries", ["name"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=200), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=False),
        sa.Column("role_name", sa.String(length=50), nullable=False),
        sa.Column("force_pw_change", sa.Boolean(), nullable=False),
        sa.Column("last_sign_in", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["role_name"], ["roles.name"], name=op.f("fk_users_role_name_roles")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
    )
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "cve_affected",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("cve_tracker_id", sa.BigInteger(), nullable=False),
        sa.Column("affected", sa.String(length=300), nullable=False),
        sa.ForeignKeyConstraint(
            ["cve_tracker_id"],
            ["cve_tracker.id"],
            name=op.f("fk_cve_affected_cve_tracker_id_cve_tracker"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cve_affected")),
    )
    op.create_table(
        "cve_pocs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("cve_tracker_id", sa.BigInteger(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["cve_tracker_id"],
            ["cve_tracker.id"],
            name=op.f("fk_cve_pocs_cve_tracker_id_cve_tracker"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cve_pocs")),
    )
    op.create_table(
        "cve_references",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("cve_tracker_id", sa.BigInteger(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.ForeignKeyConstraint(
            ["cve_tracker_id"],
            ["cve_tracker.id"],
            name=op.f("fk_cve_references_cve_tracker_id_cve_tracker"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cve_references")),
    )
    op.create_table(
        "package_dep_edges",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("monitored_package_id", sa.BigInteger(), nullable=False),
        sa.Column("depends_on", sa.String(length=300), nullable=False),
        sa.Column("depends_on_ecosystem", sa.String(length=30), nullable=False),
        sa.Column("depends_on_version", sa.String(length=100), nullable=True),
        sa.ForeignKeyConstraint(
            ["monitored_package_id"],
            ["monitored_packages.id"],
            name=op.f("fk_package_dep_edges_monitored_package_id_monitored_packages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_package_dep_edges")),
        sa.UniqueConstraint(
            "monitored_package_id", "depends_on", "depends_on_ecosystem", name="uq_package_dep_edge"
        ),
    )
    op.create_table(
        "package_vulns",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("monitored_package_id", sa.BigInteger(), nullable=False),
        sa.Column("vuln_id", sa.String(length=50), nullable=False),
        sa.Column("severity", sa.String(length=20), nullable=True),
        sa.Column("adjusted_severity", sa.String(length=20), nullable=True),
        sa.Column("kev", sa.Boolean(), nullable=False),
        sa.Column("epss", sa.Float(), nullable=True),
        sa.Column("acknowledged", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["monitored_package_id"],
            ["monitored_packages.id"],
            name=op.f("fk_package_vulns_monitored_package_id_monitored_packages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_package_vulns")),
        sa.UniqueConstraint("monitored_package_id", "vuln_id", name="uq_package_vuln"),
    )
    op.create_index(op.f("ix_package_vulns_vuln_id"), "package_vulns", ["vuln_id"], unique=False)
    op.create_table(
        "user_clients",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("client_id", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.client_id"],
            name=op.f("fk_user_clients_client_id_clients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_clients_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_clients")),
        sa.UniqueConstraint("user_id", "client_id", name="uq_user_client"),
    )
    op.create_table(
        "package_vuln_aliases",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("package_vuln_id", sa.BigInteger(), nullable=False),
        sa.Column("alias", sa.String(length=50), nullable=False),
        sa.ForeignKeyConstraint(
            ["package_vuln_id"],
            ["package_vulns.id"],
            name=op.f("fk_package_vuln_aliases_package_vuln_id_package_vulns"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_package_vuln_aliases")),
        sa.UniqueConstraint("package_vuln_id", "alias", name="uq_package_vuln_alias"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("package_vuln_aliases")
    op.drop_table("user_clients")
    op.drop_index(op.f("ix_package_vulns_vuln_id"), table_name="package_vulns")
    op.drop_table("package_vulns")
    op.drop_table("package_dep_edges")
    op.drop_table("cve_references")
    op.drop_table("cve_pocs")
    op.drop_table("cve_affected")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_techstack_entries_name"), table_name="techstack_entries")
    op.drop_index(op.f("ix_techstack_entries_client_id"), table_name="techstack_entries")
    op.drop_table("techstack_entries")
    op.drop_index(op.f("ix_scraper_items_scraper_id"), table_name="scraper_items")
    op.drop_index(op.f("ix_scraper_items_run_id"), table_name="scraper_items")
    op.drop_index(op.f("ix_scraper_items_run_at"), table_name="scraper_items")
    op.drop_table("scraper_items")
    op.drop_index(op.f("ix_monitored_packages_name"), table_name="monitored_packages")
    op.drop_index(op.f("ix_monitored_packages_client_id"), table_name="monitored_packages")
    op.drop_table("monitored_packages")
    op.drop_index(op.f("ix_ioc_threat_actors_threat_actor"), table_name="ioc_threat_actors")
    op.drop_table("ioc_threat_actors")
    op.drop_index(op.f("ix_ioc_tags_tag"), table_name="ioc_tags")
    op.drop_table("ioc_tags")
    op.drop_table("ioc_sources")
    op.drop_table("ioc_feedback")
    op.drop_index(op.f("ix_cve_tracker_cve_id"), table_name="cve_tracker")
    op.drop_index(op.f("ix_cve_tracker_client_id"), table_name="cve_tracker")
    op.drop_table("cve_tracker")
    op.drop_index(op.f("ix_cve_ticket_items_cve_id"), table_name="cve_ticket_items")
    op.drop_table("cve_ticket_items")
    op.drop_index(op.f("ix_cve_false_positives_cve_id"), table_name="cve_false_positives")
    op.drop_table("cve_false_positives")
    op.drop_table("client_countries")
    op.drop_index(op.f("ix_article_ttps_ttp_id"), table_name="article_ttps")
    op.drop_table("article_ttps")
    op.drop_index(op.f("ix_article_threat_actors_threat_actor"), table_name="article_threat_actors")
    op.drop_table("article_threat_actors")
    op.drop_index(op.f("ix_article_industries_industry"), table_name="article_industries")
    op.drop_table("article_industries")
    op.drop_index("ix_article_countries_country_role", table_name="article_countries")
    op.drop_table("article_countries")
    op.drop_index(op.f("ix_tweets_tweet_id"), table_name="tweets")
    op.drop_index(op.f("ix_tweets_author_username"), table_name="tweets")
    op.drop_table("tweets")
    op.drop_index(op.f("ix_scraper_seen_scraper_id"), table_name="scraper_seen")
    op.drop_index(op.f("ix_scraper_seen_expire_at"), table_name="scraper_seen")
    op.drop_table("scraper_seen")
    op.drop_index(op.f("ix_scraper_runs_status"), table_name="scraper_runs")
    op.drop_index(op.f("ix_scraper_runs_scraper_id"), table_name="scraper_runs")
    op.drop_index(op.f("ix_scraper_runs_run_id"), table_name="scraper_runs")
    op.drop_table("scraper_runs")
    op.drop_table("scraper_config")
    op.drop_table("roles")
    op.drop_index(op.f("ix_ransomware_victims_group_name"), table_name="ransomware_victims")
    op.drop_index(op.f("ix_ransomware_victims_country_code"), table_name="ransomware_victims")
    op.drop_table("ransomware_victims")
    op.drop_index(op.f("ix_monitored_accounts_username"), table_name="monitored_accounts")
    op.drop_table("monitored_accounts")
    op.drop_index(op.f("ix_iocs_type"), table_name="iocs")
    op.drop_table("iocs")
    op.drop_index(op.f("ix_cve_tickets_ticket_id"), table_name="cve_tickets")
    op.drop_table("cve_tickets")
    op.drop_table("clients")
    op.drop_index(op.f("ix_audit_log_username"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_at"), table_name="audit_log")
    op.drop_index(op.f("ix_audit_log_action"), table_name="audit_log")
    op.drop_table("audit_log")
    op.drop_index(op.f("ix_articles_source"), table_name="articles")
    op.drop_index(op.f("ix_articles_scraper_id"), table_name="articles")
    op.drop_index(op.f("ix_articles_news_type"), table_name="articles")
    op.drop_table("articles")
    # ### end Alembic commands ###
