"""fase 7: ioc_allowlist_entries.added_by

Revision ID: 9faf52bcc2a1
Revises: 5a456e9251a0
Create Date: 2026-09-18 18:28:01.647736

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9faf52bcc2a1"
down_revision: str | None = "5a456e9251a0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # 9 baris udah ada dari seed data Fase 5 (tools/seed/fase5_reference_data.py)
    # -- ADD COLUMN NOT NULL butuh server_default biar gak gagal di tabel yang
    # udah keisi. "system" cocok sama default Python-level model (baris lama
    # emang bukan hasil tambahan lewat API), dicabut lagi abis backfill biar
    # kolom balik jadi "wajib diisi eksplisit", bukan diam-diam default terus.
    op.add_column(
        "ioc_allowlist_entries",
        sa.Column("added_by", sa.String(length=200), nullable=False, server_default="system"),
    )
    op.alter_column("ioc_allowlist_entries", "added_by", server_default=None)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ioc_allowlist_entries", "added_by")
    # ### end Alembic commands ###
