"""fase_5_deepdarkcti_monitorx_tweet_llm_fields

Revision ID: a6f893e1319d
Revises: 5b7fe9a443b8
Create Date: 2026-09-17 19:20:20.521932

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a6f893e1319d"
down_revision: str | None = "5b7fe9a443b8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tweets",
        sa.Column("industries_impacted", postgresql.ARRAY(sa.String(length=150)), nullable=False),
    )
    op.add_column(
        "tweets",
        sa.Column("victim_countries", postgresql.ARRAY(sa.String(length=100)), nullable=False),
    )
    op.add_column(
        "tweets",
        sa.Column("actor_countries", postgresql.ARRAY(sa.String(length=100)), nullable=False),
    )
    op.add_column("tweets", sa.Column("victim_name", sa.String(length=300), nullable=True))
    op.add_column("tweets", sa.Column("incident_confidence", sa.SmallInteger(), nullable=True))
    op.add_column(
        "tweets",
        sa.Column("incident_indicators", postgresql.ARRAY(sa.String(length=50)), nullable=False),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tweets", "incident_indicators")
    op.drop_column("tweets", "incident_confidence")
    op.drop_column("tweets", "victim_name")
    op.drop_column("tweets", "actor_countries")
    op.drop_column("tweets", "victim_countries")
    op.drop_column("tweets", "industries_impacted")
    # ### end Alembic commands ###
