"""fase 7 bagian 4: tabel mindmaps

Revision ID: d5eeecc065b0
Revises: db960c735d17
Create Date: 2026-09-19 08:38:30.667776

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d5eeecc065b0"
down_revision: str | None = "db960c735d17"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "mindmaps",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("feature_type", sa.String(length=30), nullable=False),
        sa.Column("doc_id", sa.String(length=100), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("mermaid_syntax", sa.Text(), nullable=False),
        sa.Column("custom_syntax", sa.Text(), nullable=True),
        sa.Column("generated_at", sa.String(length=40), nullable=False),
        sa.Column("edited_at", sa.String(length=40), nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_mindmaps")),
        sa.UniqueConstraint("feature_type", "doc_id", name="uq_mindmap_feature_doc"),
    )
    op.create_index(op.f("ix_mindmaps_doc_id"), "mindmaps", ["doc_id"], unique=False)
    op.create_index(op.f("ix_mindmaps_feature_type"), "mindmaps", ["feature_type"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_mindmaps_feature_type"), table_name="mindmaps")
    op.drop_index(op.f("ix_mindmaps_doc_id"), table_name="mindmaps")
    op.drop_table("mindmaps")
    # ### end Alembic commands ###
