"""fase 7 bagian 4: tabel newsletters, newsletter_paywall_hints, cve_newsletter_mentions

Revision ID: db960c735d17
Revises: 25d20e532710
Create Date: 2026-09-19 08:14:41.980007

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "db960c735d17"
down_revision: str | None = "25d20e532710"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "newsletter_paywall_hints",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source", sa.String(length=200), nullable=False),
        sa.Column("paywall_likely", sa.Boolean(), nullable=False),
        sa.Column("last_seen", sa.String(length=40), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_newsletter_paywall_hints")),
    )
    op.create_index(
        op.f("ix_newsletter_paywall_hints_source"),
        "newsletter_paywall_hints",
        ["source"],
        unique=True,
    )
    op.create_table(
        "newsletters",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("week", sa.SmallInteger(), nullable=False),
        sa.Column("year", sa.SmallInteger(), nullable=False),
        sa.Column("generated_at", sa.String(length=40), nullable=False),
        sa.Column("created_by", sa.String(length=200), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("html", sa.Text(), nullable=False),
        sa.Column("sections", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_newsletters")),
    )
    op.create_table(
        "cve_newsletter_mentions",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("cve_tracker_id", sa.BigInteger(), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("source", sa.String(length=200), nullable=False),
        sa.Column("mention_date", sa.String(length=40), nullable=False),
        sa.Column(
            "added_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False
        ),
        sa.ForeignKeyConstraint(
            ["cve_tracker_id"],
            ["cve_tracker.id"],
            name=op.f("fk_cve_newsletter_mentions_cve_tracker_id_cve_tracker"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_cve_newsletter_mentions")),
        sa.UniqueConstraint("cve_tracker_id", "url", name="uq_cve_newsletter_mention"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cve_newsletter_mentions")
    op.drop_table("newsletters")
    op.drop_index(op.f("ix_newsletter_paywall_hints_source"), table_name="newsletter_paywall_hints")
    op.drop_table("newsletter_paywall_hints")
    # ### end Alembic commands ###
