"""fase 7 bagian 2: tabel rfi_requests, pir_requirements, pir_notes, source_reliability_entries

Revision ID: f5a204cd523a
Revises: 8c208279c67f
Create Date: 2026-09-18 23:13:21.845781

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f5a204cd523a"
down_revision: str | None = "8c208279c67f"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "source_reliability_entries",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("source_name", sa.String(length=200), nullable=False),
        sa.Column("analyst_name", sa.String(length=100), nullable=False),
        sa.Column("reliability_grade", sa.String(length=1), nullable=False),
        sa.Column("credibility_code", sa.String(length=1), nullable=False),
        sa.Column("admiralty_code", sa.String(length=2), nullable=False),
        sa.Column("notes", sa.Text(), nullable=False),
        sa.Column("added_date", sa.Date(), nullable=False),
        sa.Column("last_updated", sa.Date(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source_reliability_entries")),
    )
    op.create_index(
        op.f("ix_source_reliability_entries_source_name"),
        "source_reliability_entries",
        ["source_name"],
        unique=False,
    )
    op.create_table(
        "pir_requirements",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("title", sa.String(length=300), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("priority", sa.String(length=10), nullable=False),
        sa.Column("owner", sa.String(length=200), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("criteria", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("start_date", sa.Date(), nullable=True),
        sa.Column("end_date", sa.Date(), nullable=True),
        sa.Column("client_id", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.client_id"],
            name=op.f("fk_pir_requirements_client_id_clients"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pir_requirements")),
    )
    op.create_index(
        op.f("ix_pir_requirements_client_id"), "pir_requirements", ["client_id"], unique=False
    )
    op.create_table(
        "pir_notes",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("pir_id", sa.BigInteger(), nullable=False),
        sa.Column("url", sa.Text(), nullable=False),
        sa.Column("note", sa.Text(), nullable=False),
        sa.Column("analyst", sa.String(length=200), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pir_id"],
            ["pir_requirements.id"],
            name=op.f("fk_pir_notes_pir_id_pir_requirements"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_pir_notes")),
        sa.UniqueConstraint("pir_id", "url", name="uq_pir_notes_pir_url"),
    )
    op.create_index(op.f("ix_pir_notes_pir_id"), "pir_notes", ["pir_id"], unique=False)
    op.create_table(
        "rfi_requests",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("requester", sa.String(length=200), nullable=False),
        sa.Column("question", sa.Text(), nullable=False),
        sa.Column("due_date", sa.Date(), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("linked_pir_id", sa.BigInteger(), nullable=True),
        sa.Column("response", sa.Text(), nullable=False),
        sa.Column("client_id", sa.String(length=50), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["client_id"],
            ["clients.client_id"],
            name=op.f("fk_rfi_requests_client_id_clients"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["linked_pir_id"],
            ["pir_requirements.id"],
            name=op.f("fk_rfi_requests_linked_pir_id_pir_requirements"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_rfi_requests")),
    )
    op.create_index(op.f("ix_rfi_requests_client_id"), "rfi_requests", ["client_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_rfi_requests_client_id"), table_name="rfi_requests")
    op.drop_table("rfi_requests")
    op.drop_index(op.f("ix_pir_notes_pir_id"), table_name="pir_notes")
    op.drop_table("pir_notes")
    op.drop_index(op.f("ix_pir_requirements_client_id"), table_name="pir_requirements")
    op.drop_table("pir_requirements")
    op.drop_index(
        op.f("ix_source_reliability_entries_source_name"), table_name="source_reliability_entries"
    )
    op.drop_table("source_reliability_entries")
    # ### end Alembic commands ###
